services:

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    env_file: .env
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - monitoring

  telegraf:
    image: telegraf:1.36
    container_name: telegraf
    depends_on:
      - influxdb
    env_file: .env
    volumes:
      - ../../telegraf-1.36.3/etc/telegraf:/etc/telegraf:ro
    networks:
      - monitoring
    restart: unless-stopped


  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
