# Stack de Control y Automatización — RSA Seismic Network
services:
  nodered:
    image: nodered/node-red:latest
    container_name: rsa-nodered
    restart: unless-stopped
    ports:
      - "1880:1880"

    environment:
      - TZ=America/Guayaquil
      - MQTT_BROKER=${MQTT_BROKER}
    volumes:
      - /home/rsa/data/nodered:/data
    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: rsa_network