{
 "title": "Dashboard varias estaciones",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Estado estación NOM00",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM00/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM00",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM00/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM00",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM00/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM00",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM00/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM00",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM00/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado estación NOM01",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM01/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM01",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM01/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM01",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM01/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM01",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM01/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM01",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM01/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado estación NOM02",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM02/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM02",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM02/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM02",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM02/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM02",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM02/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM02",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM02/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado estación NOM03",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM03/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM03",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM03/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM03",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM03/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM03",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM03/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM03",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM03/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado estación NOM04",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM04/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM04",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM04/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM04",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM04/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM04",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM04/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM04",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM04/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado estación NOM05",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM05/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM05",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM05/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM05",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM05/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM05",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM05/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM05",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM05/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado estación NOM06",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM06/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM06",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM06/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM06",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM06/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM06",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM06/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM06",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM06/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado estación NOM07",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM07/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM07",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM07/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM07",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM07/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM07",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM07/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM07",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM07/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado estación NOM08",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM08/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM08",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM08/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM08",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM08/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM08",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM08/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM08",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM08/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado estación NOM09",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM09/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Espacio libre de disco NOM09",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM09/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura NOM09",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM09/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tiempo encendido NOM09",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM09/telemetry/state\")\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Último evento NOM09",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"rsa/seismic/smart/NOM09/telemetry/heartbeat\")\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> last()"
    }
   ]
  }
 ]
}