{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Estado de la estación",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r._field == \"status\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Espacio libre de disco GB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._field == \"disk_free_gb\")\r\n  |> filter(fn: (r) => r.topic =~ /telemetry\\/health/)\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Tiempo encendido",
   "type": "stat",
   "description": "Tiempo total (en segundos) que la estación ha permanecido encendida desde su último reinicio.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._field == \"uptime_s\")\r\n  |> filter(fn: (r) => r.topic =~ /telemetry\\/health/)\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Último evento",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._field == \"last_event\")\r\n  |> filter(fn: (r) => r.topic =~ /telemetry\\/heartbeat/)\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Temperatura de la estación °C",
   "type": "stat",
   "description": "Muestra la temperatura de la estación",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rsa\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._field == \"temp\")\r\n  |> last()\r\n"
    }
   ]
  }
 ]
}